# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
env:
  WWWROOT_DIR: "/usr/Long/software/www/"
  BUILD_SCRIPT: "#!/usr/bin/env bash
                 ti1=`date +%s`
                 ti2=`date +%s`
                 i=$(($ti2 - $ti1 ))
                 while [[ 'i'-ne '10']]
                 do
	               ti2=`date +%s`
	               i=$(($ti2 - $ti1 ))"  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # 安装node环境  
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    # 安装vuepress到本地依赖，并且构建生成静态资源  
    - run: cd ./frontend/ && ./build.sh
    # 安装yarn  
    #- name: action-yarn
    #  uses: comchangs/action-yarn@v0.1-beta  
  
    # 通过ssh的方式传输runer机器生成的dist文件夹到目标部署机器的www目录
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.2
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ env.security }}
        # Remote host
        REMOTE_HOST: ${{ secrets.host }}
        # Remote user
        REMOTE_USER: ${{ secrets.user }}
      # Remote port
        REMOTE_PORT: ${{ secrets.port }}
      # Source directory
        SOURCE: ./frontend/docs/.vuepress/blog/
      # Target directory
        TARGET: ${{ env.WWWROOT_DIR }}
      
